version: '3.8'

services:
  core:
    build: .
    container_name: core_app
    ports:
      - "9411:9411"
    environment:
      - ENV_VAR_NAME=value  
    volumes:
      - .:/app 
    depends_on:
      - db 

  db:
    image: postgres:16
    container_name: core_db
    environment:
      POSTGRES_USER: posgres
      POSTGRES_PASSWORD: 0200
      POSTGRES_DB: Intranet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
